---
- name: add repo
  command: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    
- name: install nomad
  yum:
    name: nomad
    state: installed
  notify: restart nomad
  
- name: add nomad script
  template:
    src: nomad.sh.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: "root"
    group: "root"
    mode: u=rwx,g=r,o=r
  notify: restart nomad  